name: appointment_manager
description: A Flutter project for managing appointments.

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  flutter_local_notifications: ^17.2.2
  flutter_email_sender: ^5.0.0
  timezone: ^0.9.4
  intl: ^0.18.0

flutter:
  uses-material-design: true
